# Generated by Django 5.1.4 on 2025-01-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], max_length=14)),
                ('dueDate', models.DateField()),
                ('prio', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('urgent', 'urgent')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('toDo', 'To do'), ('inProgress', 'In progress'), ('awaitFeedback', 'Await feedback'), ('done', 'Done')], default='toDo', max_length=13)),
                ('assignedContacts', models.ManyToManyField(blank=True, related_name='tasks', to='join.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('checked', 'checked'), ('unchecked', 'unchecked')], max_length=9)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.task')),
            ],
        ),
    ]
